hero1 = ("Batman", "Bruce Wayne")
hero2 = ("Spiderman", "Tobey Maguire")

new_tuple = (hero1, hero2)
print(new_tuple)
print(new_tuple[0])
print(new_tuple[1])
print(new_tuple[0][0])
print(new_tuple[0][1])
print(new_tuple[1][0])
print(new_tuple[1][1])
